name = "multicom-room"
main = "src/index.ts"
compatibility_date = "2026-09-02"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "Lobby"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Lobby"]

[vars]
TARGET_ORIGIN = "http://localhost:8788"

[observability]
enabled = true
